#!/bin/bash

# Railway Setup Helper Script
# This script generates environment variables for Railway deployment

echo "=== CAROL Bike Reddit - Railway Setup Helper ==="
echo ""

# Generate secrets
echo "📝 Generating secure secrets..."
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

echo ""
echo "✅ Generated secrets. Copy these to Railway:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BACKEND SERVICE - Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Auto-generated secrets (COPY THESE NOW!)"
echo "JWT_SECRET=$JWT_SECRET"
echo "ENCRYPTION_KEY=$ENCRYPTION_KEY"
echo ""
echo "# App configuration"
echo "NODE_ENV=production"
echo "PORT=3001"
echo ""
echo "# Reddit OAuth (REPLACE WITH YOUR VALUES!)"
echo "REDDIT_CLIENT_ID=your-reddit-client-id"
echo "REDDIT_CLIENT_SECRET=your-reddit-client-secret"
echo "REDDIT_REDIRECT_URI=https://YOUR-FRONTEND-URL.railway.app/api/accounts/oauth/callback"
echo "REDDIT_USER_AGENT=CAROLBikeEngagement/1.0"
echo ""
echo "# AI Service (CHOOSE ONE)"
echo "AI_PROVIDER=openai"
echo "OPENAI_API_KEY=sk-your-openai-key"
echo "# OR"
echo "# AI_PROVIDER=anthropic"
echo "# ANTHROPIC_API_KEY=sk-ant-your-anthropic-key"
echo ""
echo "# CORS (SET AFTER FRONTEND IS DEPLOYED)"
echo "FRONTEND_URL=https://YOUR-FRONTEND-URL.railway.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "FRONTEND SERVICE - Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Backend API URL (SET AFTER BACKEND IS DEPLOYED)"
echo "VITE_API_URL=https://YOUR-BACKEND-URL.railway.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Go to Railway dashboard: https://railway.app/dashboard"
echo "2. Find your carol-bike-reddit project"
echo "3. Add these services if not already present:"
echo "   - PostgreSQL (New → Database → PostgreSQL)"
echo "   - Redis (New → Database → Redis)"
echo "   - Backend (New → GitHub Repo → Select backend/)"
echo "   - Frontend (New → GitHub Repo → Select frontend/)"
echo ""
echo "4. For Backend service:"
echo "   - Go to Variables tab"
echo "   - Add all variables listed above"
echo "   - DATABASE_URL and REDIS_URL are auto-set by Railway"
echo ""
echo "5. For Frontend service:"
echo "   - Go to Variables tab"
echo "   - Add VITE_API_URL (use backend's public URL)"
echo ""
echo "6. Generate public domains:"
echo "   - Backend: Settings → Networking → Generate Domain"
echo "   - Frontend: Settings → Networking → Generate Domain"
echo ""
echo "7. Update callback URLs:"
echo "   - Update REDDIT_REDIRECT_URI with actual frontend URL"
echo "   - Update FRONTEND_URL with actual frontend URL"
echo "   - Update Reddit app settings at reddit.com/prefs/apps"
echo ""
echo "8. Run database migrations:"
echo "   - Backend service → 3-dot menu → Run Command"
echo "   - Run: npx prisma migrate deploy"
echo "   - Then run: npm run db:seed"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tip: Save the JWT_SECRET and ENCRYPTION_KEY above!"
echo "    You'll need them if you redeploy or add new services."
echo ""
